name: Android build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Testes
        run: ./gradlew test --stacktrace

      - name: Build Project Apk
        run: ./gradlew assembleDebug

#      - name: Upload APK on Build Artifacts
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/apk/debug/app-debug.apk

      -  name: Upload Apk to Firebase App Distribution
         uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
         with:
           appId: ${{ secrets.FIREBASE_APP_ID }}
           token: ${{ secrets.FIREBASE_CI_TOKEN }}
           groups: testers
           file: app/build/outputs/apk/debug/app-debug.apk