name: Android build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run Testes
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble